version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  odoo:
    image: odoo:17
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=admin
      - PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - "8069:8069"
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
    restart: unless-stopped

volumes:
  odoo_web_data:
  odoo_db_data: