# Odoo 17 Production Configuration for Windows Server 192.168.0.21
version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: odoo17_db
    environment:
      - POSTGRES_DB=odoo_admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - odoo-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  # Odoo Application
  odoo:
    build: .
    container_name: odoo17_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - HOST=db
      - USER=admin
      - PASSWORD=1234
      - POSTGRES_DB=odoo_admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - ODOO_RC=/opt/odoo/odoo.conf
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Suppress Python warnings
      - PYTHONWARNINGS=ignore::DeprecationWarning:pkg_resources
      - SETUPTOOLS_USE_DISTUTILS=stdlib
    volumes:
      - ./custom_addons:/opt/odoo/custom_addons:ro
      - ./addons:/opt/odoo/addons:ro
      - ./odoo.conf:/opt/odoo/odoo.conf:ro
      - odoo-web-data:/var/lib/odoo
      - odoo-log-data:/var/log/odoo
      - ./backup:/opt/odoo/backup:rw
    ports:
      - "192.168.0.21:8069:8069"    # Main Odoo web interface
      - "192.168.0.21:8072:8072"    # Long polling for chat/notifications
    restart: unless-stopped
    command: ["odoo", "-c", "/opt/odoo/odoo.conf"]
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8069/ || curl -f http://localhost:8069/web/health || wget --no-verbose --tries=1 --spider http://localhost:8069/ || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 15
      start_period: 600s
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '3.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: odoo17_redis
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # Manual backup service
  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    container_name: odoo17_backup
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_DB=odoo_admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - BACKUP_DIR=/backup
      - BACKUP_RETENTION_DAYS=7
      - ODOO_DATA_DIR=/var/lib/odoo
      # Remove BACKUP_INTERVAL for manual mode
    volumes:
      - ./backup:/backup:rw
      - odoo-web-data:/var/lib/odoo:ro
    restart: "no"  # Don't auto-restart, run manually
    networks:
      - odoo-network
    profiles:
      - backup  # Only start when explicitly requested

# Persistent volumes
volumes:
  odoo-db-data:
    driver: local
  odoo-web-data:
    driver: local
  odoo-log-data:
    driver: local
  redis-data:
    driver: local

# Network
networks:
  odoo-network:
    driver: bridge