# Odoo 17 Production Configuration for Windows Server 192.168.0.21

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: odoo17_db
    environment:
      - POSTGRES_DB=odoo_prod
      - POSTGRES_USER=odoo_prod
      - POSTGRES_PASSWORD=OdooSecure2024!
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo_prod"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - odoo-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  # Odoo Application
  odoo:
    build: .
    container_name: odoo17_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=db
      - USER=odoo_prod
      - PASSWORD=OdooSecure2024!
      - POSTGRES_DB=odoo_prod
      - POSTGRES_USER=odoo_prod
      - POSTGRES_PASSWORD=OdooSecure2024!
      - ODOO_RC=/opt/odoo/odoo.conf
    volumes:
      - ./custom_addons:/opt/odoo/custom_addons:ro
      - ./addons:/opt/odoo/addons:ro
      - ./odoo.conf:/opt/odoo/odoo.conf:ro
      - odoo-web-data:/var/lib/odoo
      - odoo-log-data:/var/log/odoo
      - ./backup:/opt/odoo/backup:rw
    ports:
      - "192.168.0.21:8069:8069"    # Main Odoo web interface
      - "192.168.0.21:8072:8072"    # Long polling for chat/notifications
    restart: unless-stopped
    command: ["odoo", "-c", "/opt/odoo/odoo.conf"]
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8069/web/health || wget --no-verbose --tries=1 --spider http://localhost:8069/web/health || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: odoo17_redis
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - odoo-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # Automatic backup service
  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    container_name: odoo17_backup
    depends_on:
      odoo:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - POSTGRES_DB=odoo_prod
      - POSTGRES_USER=odoo_prod
      - POSTGRES_PASSWORD=OdooSecure2024!
      - BACKUP_DIR=/backup
      - BACKUP_RETENTION_DAYS=7
      - ODOO_DATA_DIR=/var/lib/odoo
      - BACKUP_INTERVAL=86400  # Daily backup (24 hours in seconds)
    volumes:
      - ./backup:/backup:rw
      - odoo-web-data:/var/lib/odoo:ro
    restart: unless-stopped
    networks:
      - odoo-network

# Persistent volumes
volumes:
  odoo-db-data:
    driver: local
  odoo-web-data:
    driver: local
  odoo-log-data:
    driver: local
  redis-data:
    driver: local

# Network
networks:
  odoo-network:
    driver: bridge